site_name: '2020-1 - Elementos de Sistemas - Z01'
theme:
  name: 'material'
  features:
    - tabs
  palette:
      primary: 'white'
      accent: 'pink'

docs_dir: 'docs-src'
repo_name: 'Insper/Z01.1'
repo_url: 'https://github.com/insper/Z01.1'
edit_uri: 'edit/docs/docs-src/'

copyright: 'Copyright &copy; Rafael Corsi @ insper'

nav:
- Home:
  - 'index.md'
  - 'Critérios de Avaliação': 'Sobre-Criterios-de-Avaliacao.md'
  - 'Rubricas Projetos': 'Sobre-Rubricas.md'
  - 'Util-Corona.md'

- Aulas:
  - 'Util-Aulas.md'

- 'Projetos':
  - 'A-Ambiente-Desenvolvimento-Projeto.md'
  - 'LogiComb-Projeto.md'
  - 'ula-Projeto.md'
  - 'ula-Projeto-dicas.md'
  - 'seq-Projeto.md'
  - 'assembly-Projeto.md'
  - 'F - CPU':
      - 'cpu-Projeto.md'
      - 'cpu-Testando.md'
  - 'assembler-Projeto.md'
  - 'X-Processadores-Projeto.md'

- Labs:
  - 'A-Ambiente-Lab-1.md'
  - 'A-Ambiente-Lab-2.md'
  - 'A-Transistores-Lab-1.md'
  - 'LogiComb-Lab-1.md'
  - 'LogiComb-Lab-2.md'
  - 'ula-Lab-1.md'
  - 'ula-Lab-2.md'
  - 'ula-Lab-3.md'
  - 'ula-lab-4.md'
  - 'seq-Lab-1.md'
  - 'assembly-Lab-1.md'
  - 'assembly-Lab-2.md'
  - 'assembly-Lab-3.md'
  - 'assembly-Lab-4.md'
  - 'cpu-lab-1.md'
  - 'Lab 16: Assembler':
    - 'assembler-Lab-1.md'
    - 'assembler-Lab-1-parte-1.md'
    - 'assembler-Lab-1-parte-2.md'
    - 'assembler-Lab-1-parte-3.md'
    - 'assembler-Lab-1-parte-4.md'
    - 'assembler-Lab-1-parte-5.md'
#  - 'Resumo': 'Util-Resumo-Labs.md'
#  - '17: J VM Translator Lab 1': 'J-VMtranslator-Lab-1.md'
#  - '16: I VM Lab 1': 'I-VM-Lab-1.md'

- 'Teoria':
  - 'Teoria-Algebra-Booleana.md'
  - 'Teoria-Dados.md'
  - 'Teoria-Componentes.md'
  - 'Teoria-Aritmetica-Binaria.md'
  - 'Teoria-Aritmetica-Binaria-HW.md'
  - 'Teoria-ULA.md'
  - 'Teoria-Logica-Sequencial.md'
  - 'Teoria-Sequencial-Componentes.md'
  - 'Teoria-Z01.md'
  - 'Teoria-Assembly.md'
  - 'Teoria-Z01-mapadeMemoria.md'
  - 'Teoria-nasm-jump.md'
  - 'Teoria-Linguagem-de-Maquina.md'
  - 'Teoria-Assembler.md'
  - 'assembler-Dicas-SymbolTable.md'
  - 'Vídeo Aulas (Luciano)': 'Util-Video-Aulas.md'

- 'VHDL':
  - 'VHDL-basico.md'
  - 'VHDL-Combinacional.md'
  - 'VHDL-port-map.md'
  - 'VHDL-Sequencial.md'
  - 'VHDL-RTL.md'
  - 'VHDL-exemplos.md'

- 'Z01':
  - 'Resumo Assembly': 'Util-Resumo-Assembly.md'
  - 'Z01.1 Cheat Sheet': 'Util-Z01.1-Cheat-Sheet.md'
  - 'Instruction Set': 'Util-InstructionSet.md'
  - 'Resumo VM': 'Util-Resumo-VM.md'

- 'Estudo':
  - 'Exercicio-Algebra-Booleana-1.md'
  - 'Exercicio-Algebra-Booleana-2.md'
  - 'Exercicio-Dados-1.md'
  - 'Exercicio-Dados-2.md'
  - 'Handout Aritmetica Booleana': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Exercicio-Aritmetica-Booleana.pdf'
  - 'Lógica Sequencial - 1': 'https://forms.gle/XMsFCDMYsmz1qUP86'
  - 'Linguagem de Máquina - 1': 'https://forms.gle/6jNZR4CAELJ69ZjXA'
- 'Avaliações':
    - 'Avaliacoes.md'

- Útil:
  - 'Util-Comecando-novo-projeto.md'
  - 'Util-vixi-sou-scrum.md'
  - 'Dicas git': 'Util-Dicas-GIT.md'
  - 'Util-Dicas-Travis.md'
  - 'Infraestrutura': 'Util-Infraestrutura.md'
  - 'Util-VM-Linux.md'

- Atendimento:
  - 'Atendimento.md'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'translate_admonitions.js'

plugins:
    - search

# Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

